source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'jbuilder', '~> 2.0'
# 图片上传
gem 'kaminari', '~> 0.16.3'
gem 'carrierwave', '~> 0.10.0'
gem 'mini_magick', '4.5.0'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
gem 'mysql2', '~>0.4.2', group: :production

gem 'sqlite3', group: [:development, :test]
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
group :production do
  gem 'unicorn', '~> 5.0'
  gem 'unicorn-worker-killer', '~> 0.4.4'
end
gem 'redis', '~>3.2.2'
#gem 'zxing', '~> 0.4.0'
#gem 'json', '1.8.3'
